version: '2.1'
services:
  redis:
    image: redis
    restart: 'always'
    read_only: true
    ports:
      - '6379:6379'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    env_file:
      - app/env/.env-docker
